#!/bin/bash
cargo build -Z build-std=std,panic_abort --target x86_64-unknown-linux-gnu --release &&
cp target/x86_64-unknown-linux-gnu/release/libtest_plugin.so test.plugin &&
target/x86_64-unknown-linux-gnu/release/dyn-load-impl
